apply plugin: 'com.android.application'

android {
    namespace "com.yilanharf.oyunu"
    compileSdk 34

    defaultConfig {
        applicationId "com.yilanharf.oyunu"
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            def keystoreFile = project.hasProperty('android.injected.signing.store.file')
                ? project.property('android.injected.signing.store.file')
                : null
            if (keystoreFile) {
                storeFile file(keystoreFile)
                storePassword project.property('android.injected.signing.store.password')
                keyAlias project.property('android.injected.signing.key.alias')
                keyPassword project.property('android.injected.signing.key.password')
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            def hasKeystore = project.hasProperty('android.injected.signing.store.file')
            if (hasKeystore) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
}
